# Site settings
title:       Project Title
author:      James Wigger
description: "A short introduction of your project, this will be displayed in the meta description and the main banner area."
baseurl:     ""
url:         "http://username.github.io/project"
hero_image: "/images/default.jpg"
homepage: "http://yoursite.com"

# Google analytics
google_analytics:

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink: none
sass:
  style: :compressed
  compressed: true
gems:
  - jekyll-sitemap